// pages/news.vue
<template>
  <div class="news">
    <news-article-summary-card
      v-for="(article, index) in news"
      :key="index"
      :article="article"
      class="ma-2"
    />
  </div>
</template>

<script>
import NewsArticleSummaryCard from '~/components/NewsArticleSummaryCard'
import newsJson from '~/assets/json/news.json'

export default {
  components: {
    NewsArticleSummaryCard,
  },

  data: () => ({
    news: {
      type: Array,
    },
  }),

  async created() {
    if (newsJson) {
      this.news = newsJson
    } else {
      const news = await this.$axios.$get(
        'https://script.google.com/macros/s/AKfycbzHGIXhIr70kYpljKadfT_XMxBWo9wGSW73n9XbuhZi8uPFlyw/exec'
      )
      this.news = news
    }
  },

  head() {
    return {
      title: 'News',
    }
  },
}
</script>

// src/pages/news.jsx
import React from 'react';
import Head from 'next/head';
import PropTypes from 'prop-types';
import fetch from 'node-fetch';
import NewsList from '../components/NewsList';

const News = ({ news }) => {
  return (
    <React.Fragment>
      <Head>
        <title>News | MLJP SCRIM</title>
      </Head>

      <NewsList news={news} />
    </React.Fragment>
  );
};

News.propTypes = {
  news: PropTypes.array,
};

export async function getStaticProps() {
  const res = await fetch(
    'https://script.google.com/macros/s/AKfycbzdg3_jf8jj5mwNYRmz8rVJ7JuVjCwhCmY7MTH0LBrmRD-4tKM/exec'
  );
  const news = await res.json();

  return {
    props: {
      news,
    },
  };
}

export default News;
