// pages/stats.vue
<template>
  <div class="stats">
      <v-card v-if="!stats.length" outlined class="text-center ma-2 pa-8">
        データがありません
      </v-card>
    <scrim-result-summary-card
      v-for="(result, index) in stats"
      :key="index"
      :result="result"
      class="ma-2"
    />
  </div>
</template>

<script>
import ScrimResultSummaryCard from '~/components/ScrimResultSummaryCard'
import statsJson from '~/assets/json/stats.json'

export default {
  components: {
    ScrimResultSummaryCard,
  },

  data: () => ({
    stats: {
      type: Array,
    },
  }),

  async created() {
    if (statsJson) {
      this.stats = statsJson
    } else {
      const stats = await this.$axios.$get(
        'https://script.google.com/macros/s/AKfycbzHGIXhIr70kYpljKadfT_XMxBWo9wGSW73n9XbuhZi8uPFlyw/exec'
      )
      this.stats = stats
    }
  },

  head() {
    return {
      title: 'Stats',
    }
  },
}
</script>

// src/pages/stats.jsx
import React from 'react';
import Head from 'next/head';
import PropTypes from 'prop-types';
import fetch from 'node-fetch';
import Container from '@material-ui/core/Container';
import Box from '@material-ui/core/Box';
import ResultCard from '../components/ResultCard';

const Stats = ({ stats }) => {
  const NoData = () => {
    if (stats.length < 1) {
      return (
        <Container>
          <Box p={8} textAlign="center">
            データがありません
          </Box>
        </Container>
      );
    }

    return null;
  };

  return (
    <React.Fragment>
      <Head>
        <title>Stats | MLJP SCRIM</title>
      </Head>

      <NoData />

      {stats.map((stat) => (
        <ResultCard stat={stat} key={stat.uid} />
      ))}
    </React.Fragment>
  );
};

Stats.propTypes = {
  stats: PropTypes.array,
};

export async function getStaticProps() {
  const res = await fetch(
    'https://script.google.com/macros/s/AKfycbzHGIXhIr70kYpljKadfT_XMxBWo9wGSW73n9XbuhZi8uPFlyw/exec'
  );
  const stats = await res.json();

  return {
    props: {
      stats,
    },
  };
}

export default Stats;
