// pages/teams.vue
<template>
  <div class="teams-container mt-3">
    <div v-if="clans.length" class="teams-list">
      <div v-for="clan in clans" :key="clan.uid" class="teams-list-item">
        <v-card tile :to="'team/' + clan.uid">
          <v-img eager src="https://cdn.vuetifyjs.com/images/cards/docks.jpg" />
          <v-card-subtitle class="accent--text">
            [{{ clan.tag }}]
          </v-card-subtitle>
          <v-card-title>
            {{ clan.name }}
          </v-card-title>
        </v-card>
      </div>
    </div>
  </div>
</template>

<script>
import clansJson from '~/assets/json/teams.json'

export default {
  data: () => ({
    clans: {
      type: Array,
    },
  }),

  async created() {
    if (clansJson) {
      this.clans = clansJson
      return
    }

    const clans = await this.$axios.$get(
      'https://script.google.com/macros/s/AKfycbxtkRN9bqBbUyUj43B7epmVTkMz0LT5JK2Jx6qjxNuux2FZV4uu/exec'
    )
    this.clans = clans
  },
}
</script>

<style scoped>
.teams-container {
  margin: 0 12px 0 0;
}

.teams-list {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}

.teams-list-item {
  width: calc(50% - 12px);
  margin: 0 0 12px 12px;
}

.v-card__subtitle {
  padding: 8px 8px 0;
}

.v-card__title {
  padding: 0 8px;
}
</style>

// src/pages/teams.jsx
import React from 'react';
import PropTypes from 'prop-types';
import fetch from 'node-fetch';
import { makeStyles } from '@material-ui/core/styles';
import Grid from '@material-ui/core/Grid';
import Box from '@material-ui/core/Box';
import Paper from '@material-ui/core/Paper';
import Typography from '@material-ui/core/Typography';
import { indigo } from '@material-ui/core/colors';

const useStyles = makeStyles((theme) => ({
  card: {
    width: '100%',
  },
  item: {
    display: 'flex',
  },
  nameWrap: {
    wordBreak: 'break-word',
    padding: theme.spacing(1),
  },
  name: {
    [theme.breakpoints.down('xs')]: {
      lineHeight: '1em',
    },
  },
  logo: {
    display: 'block',
    width: '100%',
    height: 'auto',
    backgroundColor: indigo[500],
  },
}));

const Teams = ({ teams }) => {
  const classes = useStyles();

  return (
    <Box m={1}>
      <Grid container spacing={1}>
        {teams.map((team) => (
          <Grid item xs={6} sm={3} key={team.name} className={classes.item}>
            <Paper square className={classes.card}>
              <img
                src={
                  team.logoUrl
                    ? `/images/logos/${team.logoUrl}.jpg`
                    : '/images/logos/default.png'
                }
                alt={team.name}
                className={classes.logo}
              />
              <Box className={classes.nameWrap}>
                <Typography
                  variant="caption"
                  color="primary"
                  className={classes.name}
                >
                  [{team.tag}]
                </Typography>{' '}
                <Typography
                  variant="h6"
                  component="h2"
                  className={classes.name}
                >
                  {team.name}
                </Typography>
              </Box>
            </Paper>
          </Grid>
        ))}
      </Grid>
    </Box>
  );
};

Teams.propTypes = {
  teams: PropTypes.array,
};

export async function getStaticProps() {
  const res = await fetch(
    'https://script.google.com/macros/s/AKfycbxtkRN9bqBbUyUj43B7epmVTkMz0LT5JK2Jx6qjxNuux2FZV4uu/exec'
  );
  const teams = await res.json();

  return {
    props: {
      teams,
    },
  };
}

export default Teams;
